module.exports = [
	{
		id: 1,
		user_first_name: "Terry",
		user_surname: "Berger",
		email: "terryberger@gmail.com",
		sample_user: true,
	},
	{
		id: 2,
		user_first_name: "Dwight",
		user_surname: "Ray",
		email: "dwigthray@gmail.com",
		sample_user: true,
	},
	{
		id: 3,
		user_first_name: "Zach",
		user_surname: "Highley",
		email: "z.highley@outlook.com",
		sample_user: true,
	},
	{
		id: 4,
		user_first_name: "Mark",
		user_surname: "Winters",
		email: "mark.winter@gmail.com",
		sample_user: true,
	},
	{
		id: 5,
		user_first_name: "Kenzie",
		user_surname: "Lang Malakas",
		email: "k.lang-malakas@icloud.com",
		sample_user: true,
	},
	{
		id: 6,
		user_first_name: "Joshua",
		user_surname: "Scott",
		email: "joshscott78@web.com",
		sample_user: true,
	},
	{
		id: 7,
		user_first_name: "Anna",
		user_surname: "Lee",
		email: "anna_lee_@outlook.com",
		sample_user: true,
	},
	{
		id: 8,
		user_first_name: "Tyler",
		user_surname: "Mann",
		email: "licensing@jukinmedia.com",
		sample_user: true,
	},
	{
		id: 9,
		user_first_name: "Mark",
		user_surname: "Horvath",
		email: "markhorvath@invisiblepeople.com",
		sample_user: true,
	},
];
