module.exports = [
	{
		video_id: 1,
		time_witness_first_name: "Mary",
		time_witness_surname: "Shainberg",
		age: "100",
		date_of_birth: "1917-05-04",
		place_of_birth: "Austin, Texas, USA",
		places_lived: "USA",
		gender: "female",
		topics: "life, youth, happiness",
		story_summary:
			"This is my great-grandmother, Mary Shainberg - better known by my family as “Gigi”. She is a truly inspiring, amazing and ambitious woman and I hope to be like her one day. I wanted to ask her a few questions and let her tell some of her stories.",
		sample_video: true,
		video_link: "k7uco9eG5kA",
		user_id: "1",
		date_of_interview: "2017-05-05",
	},
	{
		video_id: 2,
		time_witness_first_name: "Ayda",
		time_witness_surname: "Magnaye-Ray",
		age: "83",
		date_of_birth: null,
		place_of_birth: null,
		places_lived: null,
		gender: "female",
		topics: "life, faith, happiness",
		story_summary: "Asking my 83 year old grandmother about her life",
		sample_video: true,
		video_link: "e8pWNn176RY",
		user_id: "2",
		date_of_interview: "2022-03-24",
	},
	{
		video_id: 3,
		time_witness_first_name: "Elizabeth",
		time_witness_surname: "Padre-Piswinia",
		age: "90",
		date_of_birth: "1932-01-01",
		place_of_birth: null,
		places_lived: null,
		gender: "female",
		topics: "life advice, happiness",
		story_summary: "Asking my 90 year old grandmother about her life",
		sample_video: true,
		video_link: "YhGmul5G77I",
		user_id: "2",
		date_of_interview: "2022-03-23",
	},
	{
		video_id: 4,
		time_witness_first_name: "John",
		time_witness_surname: "Highley",
		age: "97",
		date_of_birth: "1918-02-15",
		place_of_birth: "London, UK",
		places_lived: "England, US",
		gender: "male",
		topics: "WWII",
		story_summary:
			"I had a very important question for my grandpa, and the answer was life-changing. My grandpa is 97-years old. He lives 3000 miles away and I love him very much. I wanted to make sure, for my sake, for my family's sake, for the world's sake, that there was some record of his story, a memory of the amazing man he is. Here is my journey traveling 3000 miles to interview my grandpa.",
		sample_video: true,
		video_link: "TH1a1akbI_s",
		user_id: "3",
		date_of_interview: "2021-11-05",
	},
	{
		video_id: 5,
		time_witness_first_name: "Dick",
		time_witness_surname: "Winters",
		age: "91",
		date_of_birth: null,
		place_of_birth: "New York, USA",
		places_lived: "USA, Germany",
		gender: "male",
		topics: "WWII",
		story_summary: "Grandpa, were you a hero in the war?",
		sample_video: true,
		video_link: "V6TrbOexkUc",
		user_id: "4",
		date_of_interview: "2012-01-03",
	},
	{
		video_id: 6,
		time_witness_first_name: "Johnny",
		time_witness_surname: "Lontoc Malakas",
		age: null,
		date_of_birth: null,
		place_of_birth: "Philippines",
		places_lived: "Philippines",
		gender: "male",
		topics: "WWII",
		story_summary: "asking my grandpa on world war 2",
		sample_video: true,
		video_link: "E9d_Z5LUbkg",
		user_id: "5",
		date_of_interview: "2021-12-26",
	},
	{
		video_id: 7,
		time_witness_first_name: "Gerd Friedrich Franz",
		time_witness_surname: "Schmitz",
		age: null,
		date_of_birth: "1927-05-02",
		place_of_birth: "Germany",
		places_lived: "Germany, Netherlands",
		gender: "male",
		topics: "WWII, Nazi Germany",
		story_summary:
			"Growing up in Germany in the 1930’s, Gert Schmitz was drafted into the Hitler Youth, witnessed the start of World War II, and joined the Luftwaffe by the time he was 17 years old. But his dreams of flight would be crushed when he was sent to the Western Front to fight the advancing Allied Forces with a disoriented and dwindling German Army.",
		sample_video: true,
		video_link: "3D0Uw-y9mrk",
		user_id: "6",
		date_of_interview: "2021-04-02",
	},
	{
		video_id: 8,
		time_witness_first_name: "Bernard",
		time_witness_surname: "Albertson",
		age: "77",
		date_of_birth: "1938-07-14",
		place_of_birth: "USA",
		places_lived: "USA",
		gender: "male",
		topics: "life advice, technology",
		story_summary:
			"Bernard Albertson tells a story of his life and shares many memories and ideas in his own words. Our Father Bernard Albertson loved writing books and making videos. He self published his books and they are available on Amazon in Paperback and Digital Books for download.",
		sample_video: true,
		video_link: "ERRKmVlCz5A",
		user_id: "7",
		date_of_interview: "2020-10-31",
	},
	{
		video_id: 9,
		time_witness_first_name: "Unknown",
		time_witness_surname: "Homeless guy",
		age: "40",
		date_of_birth: null,
		place_of_birth: null,
		places_lived: null,
		gender: "male",
		topics: "life advice, prison, homelessness",
		story_summary:
			"Homeless guy spits some truth. His story after leaving prison and trying to come back, just realizing society does not have a place for people with a felony.",
		sample_video: true,
		video_link: "RfU8TUZRtZg",
		user_id: "8",
		date_of_interview: "2018-06-30",
	},
	{
		video_id: 10,
		time_witness_first_name: "Keith",
		time_witness_surname: "Unknown",
		age: "35",
		date_of_birth: null,
		place_of_birth: null,
		places_lived: "Los Angeles, USA",
		gender: "male",
		topics: "homelessness, drugs, addiction",
		story_summary:
			"Keith is open about being addicted to heroin. When the market crashed Keith lost his job in the housing industry. He was addicted to painkillers and started to use heroin because it was cheaper. Before you judge Keith you should know drugs like heroin and crack cocaine will completely take your life away. Alcohol can too, but drug addiction is much worse. Keith talks very candid about the grip of heroin on a life. It takes your life away. Keith may sound like he enjoys street life, but really listen to what he is saying. He is not happy and wants to get out. Listen to his first wish. He just does not know how to stop heroin.",
		sample_video: true,
		video_link: "H6ZFzEW7_Q4",
		user_id: "9",
		date_of_interview: "2019-09-21",
	},
	{
		video_id: 11,
		time_witness_first_name: "EJ (Daniel)",
		time_witness_surname: "Unknown",
		age: "18",
		date_of_birth: null,
		place_of_birth: null,
		places_lived: "USA",
		gender: "male",
		topics: "homelessness, youth",
		story_summary:
			"'On the streets, you don't wish for things. You just wait for them to happen. Because you cannot control really anything', EJ responded trying to think of a second and third wish. EJ is homeless in Hollywood. He is 18, and when he told me he has been homeless for 11 years, I could not even comprehend to do the math.",
		sample_video: true,
		video_link: "3N2z5O2xYKw",
		user_id: "9",
		date_of_interview: "2013-07-15",
	},
	{
		video_id: 12,
		time_witness_first_name: "Delilah",
		time_witness_surname: "Unknown",
		age: "23",
		date_of_birth: null,
		place_of_birth: null,
		places_lived: "USA",
		gender: "female",
		topics: "homelessness",
		story_summary:
			"Delilah is young and homeless. She says that previously she worked in a Beverly Hills hair salon and that homelessness is much better than cutting hair for angry, mean rich ladies!",
		sample_video: true,
		video_link: "rWxVwTVU15Q",
		user_id: "9",
		date_of_interview: "2017-05-06",
	},
	{
		video_id: 13,
		time_witness_first_name: "EJ (Daniel)",
		time_witness_surname: "Unknown",
		age: "18",
		date_of_birth: null,
		place_of_birth: null,
		places_lived: "USA",
		gender: "male",
		topics: "homelessness, youth",
		story_summary:
			"'On the streets, you don't wish for things. You just wait for them to happen. Because you cannot control really anything', EJ responded trying to think of a second and third wish. EJ is homeless in Hollywood. He is 18, and when he told me he has been homeless for 11 years, I could not even comprehend to do the math.",
		sample_video: true,
		video_link: "3N2z5O2xYKw",
		user_id: "9",
		date_of_interview: "2013-07-15",
	},
];
