module.exports = [
	{
		video_id: 1,
		time_witness_first_name: "=",
		time_witness_surname: "",
		age: "",
		date_of_birth: "",
		place_of_birth: "",
		places_lived: "",
		gender: "",
		topics: "",
		story_summary: "",
		sample_video: true,
		video_link: "",
		user_id: "",
		date_of_interview: "",
	},
	{
		video_id: 2,
		time_witness_first_name: "=",
		time_witness_surname: "",
		age: "",
		date_of_birth: "",
		place_of_birth: "",
		places_lived: "",
		gender: "",
		topics: "",
		story_summary: "",
		sample_video: true,
		video_link: "",
		user_id: "",
		date_of_interview: "",
	},
	{
		video_id: 3,
		time_witness_first_name: "=",
		time_witness_surname: "",
		age: "",
		date_of_birth: "",
		place_of_birth: "",
		places_lived: "",
		gender: "",
		topics: "",
		story_summary: "",
		sample_video: true,
		video_link: "",
		user_id: "",
		date_of_interview: "",
	},
];
